export enum RoleIdType {
  NONE = 0,
  ADMIN = 1,
  OUTLET_OWNER = 2,
  COMMUNITY_OUTLET = 3, // Not Use
  COMMUNITY_SELLER_OUTLET = 4, // OCS = Outlet Community Seller
  CONSUMER = 5,
  COMMUNITY_SELLER_HEINEKEN = 6, // HCS = Heineken Community Seller
  SUPPER_ADMIN = 10,
}

export enum RoleNameType {
  NONE = 'NONE',
  ADMIN = 'ADMIN',
  OUTLET_OWNER = 'OUTLET_OWNER',
  COMMUNITY_OUTLET = 'COMMUNITY_OUTLET', // Not Use
  COMMUNITY_SELLER_OUTLET = 'COMMUNITY_SELLER_OUTLET', // OCS = Outlet Community Seller
  CONSUMER = 'CONSUMER',
  COMMUNITY_SELLER_HEINEKEN = 'COMMUNITY_SELLER_HEINEKEN', // HCS = Heineken Community Seller
  SUPPER_ADMIN = 'SUPPER_ADMIN',
}